#!/bin/sh

### Start xteve

sleep 20

# so return traffic that went through VPN works

gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NET} via $gw dev eth0

# start
xteve -port=34400 -config=/root/.xteve/
